### ISSUE TITLE
Support Writing Events to Filesystem

### ISSUE THREAD

**Issue by mlmitch** [weaklayer/gateway#3]
Don't want events going to stdout forever.
Writing to the filesystem feels like the lowest common denominator for being able to integrate Weaklayer data into other systems (e.g. SIEM/SOAR).

Current idea for design:
- use config to specify an output directory
- subdirectories are created based on sensor group
- one file at a time being appended to in these subdirectories, rotated by time/size
- data from many sensors in the same group goes to the same file

This setup is desired mainly because we don't want to scale the number of open file with the number of sensors.
Scaling with the number of groups is more reasonable.
Can later add ability to write to multiple files for a group simultaneously if throughput is limited by this.

**Comment by mlmitch** [comment]
**How to format output files**
One line per event in json format is natural.
The output files can be valid json making the file one giant json array.
Can still be streamed in line by line.
Having these two options should facilitate integration with downstream consumption.

**Broadcast To multiple Outputs?**
A future scenario I'm picturing is something like "I want to send data to a SIEM/SOAR and send it to blob storage for archiving".
A scenario like this could easily arise with wanting to write to two filesystem locations.

**How to format configuration**
Need to allow specification of an output directory.
Multiple output destinations hints at an array of outputs in the config file.
Maybe something like this
```
event:
  outputs:
  - type: stdout
  - type: filesystem
    directory: /tmp/weaklayer
  - type: filesystem
    directory: /nfs/departmentb/weaklayer
```

**Implementation Ideas**
HTTP event submission blocks until all events are written to all outputs.
Return an error if they are not processed successfully.
Log if they are not processed successfully.
Use one goroutine per file.
New file gets a new goroutine - this will allow better file handling guarantees like `defer` file close will always close the file on goroutine exit.
Each file is fed events through a channel.
Need some sort of acknowledgement mechanism if we want at least once processing.

**Comment by mlmitch** [comment]
Currently we are in an "At most once" processing mode. Each event is processed once and it is thrown out if there is an error.
This is a simpler processing guarantee to maintain and should be more performant.
Switching to "At least once" is probably desired in the future, but it requires sensor implementation as well to be meaningful.
For this ticket, the gateway will stay in "at most once" processing mode.
This will avoid the need to track and acknowledge events.
The sensor will receive a 200 when events pass validation and are handed off into the output processing pipeline.

**Comment by mlmitch** [comment]
Settled on output config similar to above. Looks like this:
```
outputs:
- type: stdout
- type: filesystem
  # the top directory where the gateway will write events to the filesystem
  directory: ./weaklayer-events
  # the time, in microseconds, that a file will be closed after
  age: 30000000
  # the size, in bytes, that a file will be closed after
  size: 10000
```
